export const petTableHeads = [
  "Image",
  "Name",
  "Species",
  "Breed",
  "Age",
  "Size",
  "SpecialNeeds",
  "Gender",
  "Location",
  "Description",
  "Temperament",
  "Adoption Status",
  "Health Status",
  "Adoption Requirements",
  "Created At",
  "Updated Date",
  "Adoption Requests",
  "Edit",
  "Remove",
];
